---
title: "R package fdcov"
author: "Adam B. Kashlak, Alessandra Cabassi"
date: "`r Sys.Date()`"
output:
    rmarkdown::html_vignette:
        toc: true
        toc_depth: 2
        number_sections: true
vignette: >
  %\VignetteIndexEntry{R package fdcov}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The R package `fdcov` (**F**unctional **D**ata **Cov**ariance) contains a collection of tools for performing statistical inference on functional data specifically through an analysis of the covariance structure of the data. It includes two methods for performing a k-sample test for equality of covariance in `ksample.perm` and `ksample.com` and two methods for performing a 2-sample test `ksample.gauss` and `ksample.vstab`. For supervised and unsupervised learning, it contains a method to classify functional data with respect to each category's covariance operator in `classif.com`, and it contains a method to cluster functional data, `cluster.com`, again based on the covariance structure of the data.

The current version of this package assumes that all functional data is sampled on the same grid at the same intervals. Future updates are planned to allow for the below methods to interface with the fda package and its functional basis representations of the data.

# k-sample test for the equality of covariance operators

There are two methods for performing a k-sample test for equality of covariance operators.


